# Training configuration
model_path: null
data_folders:
  - "/media/jimmy/MyData/Data/carla/20230716-090013"
  - "/media/jimmy/MyData/Data/carla/20230716-095740"
  - "/media/jimmy/MyData/Data/carla/20230718-060304"
  - "/media/jimmy/MyData/Data/carla/20230718-072650"
  - "/media/jimmy/MyData/Data/carla/20230718-074806"
  - "/media/jimmy/MyData/Data/carla/20230718-080318"
batch_size: 128
learning_rate: 0.001
gamma: 0.98
target_model_update_freq: 1000
moving_average_window: 100
log_freq: 100
print_freq: 100
show_freq: 10
log_dir: "/home/jimmy/Desktop/CARLA_PROJ/Logs"
save_freq: 500
save_dir: "/home/jimmy/Desktop/CARLA_PROJ/Checkpoints"